### ISSUE TITLE
[FEAT] Survey-1 페이지 구성

### ISSUE THREAD

**Issue by yoon-junseo** [CodingWasabi/eotteok_frontend#10]
## 설명
- 설문 조사 1페이지 구성

## ToDo
- [x] 페이지 구성
   - [x] progressBar
      - [x] 짱구 이미지 
      - [x] width에 따라 움직이는 애니메이션
   - [x] 질문 제목
   - [x] 질문 항목
   - [x] 이전, 다음 버튼 (질문 항목이 선택된 경우에만 넘어갈 수 있게)
- [x] 리덕스 설정
   - [x] 스토리북에 적용
   - [x] survey store 설정
      - [x] action
      - [x] type
      - [x] reducer
   - [x] hook 설정
      - [x] state
      - [x] action
