### ISSUE TITLE
[FEAT] 시험정보 입력 페이지 구성

### ISSUE THREAD

**Issue by yoon-junseo** [CodingWasabi/eotteok_frontend#12]
## 설명
- 시험정보를 입력하는 페이지를 구성한다. 
- 닉네임 입력을 모듈에 추가한다.

## ToDo
- [x] 배경 이미지 설정
- [x] 입력 컴포넌트 (입력이 안되어 있다면 회색, 입력이 되면 초록색 처리)
   - [x] 과목명 입력
   - [x] 날짜 입력
   - [x] 시간 입력
- [x] 남은 공부 시간 선택 (만들어둔 컴포넌트 활용)
- [x] 등록하기 버튼
   - [x] 과목명, 날짜, 시간, 남은 공부 시간이 모두 선택 되어야 등록하기 버튼을 활성화 시킨다.
- [x] 시험 목록
   - [x] 시험 목록(X) -> 시험정보 입력을 유도하는 텍스트를 보여준다.
   - [x] 시험 목록(O) -> 시험 목록을 보여준다          
- [x] 시험 정보 입력 중에 수정
   - [x] 연필 버튼 클릭 
      - [x] 연필 버튼을 누르면 수정이 가능하다.
      - [x] 연필 버튼을 누르면 과목명 컴포넌트의 border 색상이 변경된다.
      - [x] 클릭 되지 않은 컴포넌트는 배경색이 변경된다.
      - [x] 등록하기 버튼이 수정하기 버튼으로 변경된다.
- [x] 닉네임 모듈 추가
   - [x] type
   - [x] action
   - [x] reducer
   - [x] hook
   - [x] 닉네임 페이지에 적용
