### ISSUE TITLE
[FEAT] 결과 페이지 화면 구성

### ISSUE THREAD

**Issue by yoon-junseo** [CodingWasabi/eotteok_frontend#17]
## 설명
- 결과 페이지를 구성한다.

## ToDo
- [x] 날짜 선택 X,  댓글 X
   - [x] 댓글 입력창을 흐리게 보이게 한다.
   - [x]  날짜 선택하고 댓글을 남겨보시지 !를 화면에 나타낸다.
- [x] 날짜 선택 X, 댓글 O
   - [x] 댓글을 랜덤으로 보여준다.
   - [x] 댓글을 보여주는 화면을 흐리게 나타낸다.
   - [x] 날짜 선택하고 댓글을 확인해 보시지!를 화면에 나타낸다.
- [x] 날짜 선택 O, 댓글 X
   - [x] 댓글 입력창을 보이게 한다.
- [x] 날짜를 선택 O, 댓글 O
   - [x] 해당 하는 날짜의 시험 과목을 보여준다.
   - [x] 댓글 목록을 보여준다.
   - [x] 댓글 입력이 가능하다.
- [x] 달력 공유해 보시지 버튼을 화면에 띄운다.
- [x] 시험정보 수정해 보시지를 화면에 띄운다.
- [x] 초기화 하기를 화면에 띄운다.
- [x] 성향에 따라서 성향에 대한 결과를 보여준다.
- [x] 댓글 입력
   - [x] 캐릭터 이미지 변경이 가능해야 한다. 
   - [x] redux
- [x] 시험 목록
   - [x] 연필을 누르면 시험 정보 수정 페이지로 이동한다.
   - [x] 스크롤 가능하게 한다.
