### ISSUE TITLE
[FEAT] 결과 페이지 기능 추가

### ISSUE THREAD

**Issue by yoon-junseo** [CodingWasabi/eotteok_frontend#19]
## 설명
- 바뀐 내용에 따라서 결과 페이지에 추가 기능 구현

## ToDo
- [x] tendency 이미지 35개 추가
- [x] tendency에 맞는 이미지 렌더링
- [ ] Calendar
   - [x] xx일 기준으로 얼마나 남았지?
   - [ ] xx일 공부 이 정도는 해야지?
   - [x] xx일 댓글 보시지?
   - [x] 댓글 입력 위치랑 댓글 목록 위치 변경
- [x] Exam
   - [x] ExamTime
