### ISSUE TITLE
[FIX] QA

### ISSUE THREAD

**Issue by yoon-junseo** [CodingWasabi/eotteok_frontend#26]
## 설명
- QA 반영

## ToDo
- [x] 설문 Q1 -> 이전 버튼 비활성화 색상 적용
- [x] 설문 Q5 
   - [x] 텍스트 크기 키우기
   - [x] 아이폰 12 pro 기준 슬라이더로 넘어갈 다음 항목이 살짝 보임 
- [ ] 결과 페이지
   - [x] 일러스트 비율 유지
   - [ ] 시험 리스트 컨테이너에 스크롤 생김 -> swipe 적용
   - [x] 과목별 공부 시간이 더 상단으로 오도록 수정
   - [x] 댓글 입력창과 아래 표시되는 댓글 목록 사이 여백 좁히기
- [x] 사파리 기준 a태그 텍스트 파란색 색상 수정
- [x] 사파리 기준 상단 주소 입력창으로 인한 스크롤
- [ ] 만든이 페이지 추가
- [x] 시험 정보 입력 -> 기본 값을 현재 시각이 아니라 6월 1일 12:00로 수정
- [x] M_1 컬러 코드 값 변경
