### ISSUE TITLE
[FEAT] 공통 컴포넌트 생성

### ISSUE THREAD

**Issue by yoon-junseo** [CodingWasabi/eotteok_frontend#6]
## 설명
- 공통적으로 사용되는 컴포넌트 생성

## ToDo
- [x] 아이콘 SVG 혹은 PNG
   - [x] 어떡하지
   - [x] 질문에 쓰일 캐릭터 (짱구, 철수, ...)
   - [x] 짱구 5개
   - [x] 댓글에 쓰일 캐릭터 5개
   - [x] 연필
   - [x] 화살표
   - [x] 전송 버튼
   - [x] 공유 (연예인 공유 아님ㅋㅋ)
- [x] 컴포넌트
   - [x] 질문 컴포넌트
   - [x] 1번 ~ 5번 숫자 컴포넌트
   - [x] 대답 컴포넌트
   - [x] 버튼 컴포넌트
      - [x] 이전
      - [x] 다음
      - [x] 추가
      - [x] 넘기시지 (M_2)
      - [x] 공유해보시지
      - [x] 달력으로 돌아가기 (M_4)
      - [x] 시험 정보 수정해보시지
   - [x] 댓글
      - [x] 입력창
      - [x] 댓글 아이템
      - [x] 캐릭터 선택창 
   - [x] 시험 정보 입력
      - [x] 과목명 입력 input 
      - [x] 과목명 item
