### ISSUE TITLE
[FEAT] 메인 페이지 & 닉네임 입력 페이지 구성

### ISSUE THREAD

**Issue by yoon-junseo** [CodingWasabi/eotteok_frontend#8]
## 설명
- 메인 페이지 구성
- 닉네임 입력 페이지 구성 및 라우팅 설정

## ToDo
- [x] 배경 이미지 설정
- [x] 메인 페이지
   - [x] 시작하기 버튼 생성
   - [x] 메인 페이지 구성
   - [x] 시작하기 버튼 클릭시 닉네임 입력 페이지로 이동
- [x] 닉네임 입력 페이지
   - [x] API 제외하고 구성
   - [x] 다음 클릭시, 설문조사 페이지로 이동
